package UI;

import Core.Confirmation;
import Core.Functions;
import Core.Items;
import Core.TableHandler;
import User.Data;
import User.ManageUser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Mellisa
 */
public class AdminPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPage.class.getName());

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        loadData();
    }
    
    //called Functions for the basic CRUD of product and also updating of clerk or admins
    Functions function = new Functions();
    //called Confirmation for the updating of product
    Confirmation confirm = new Confirmation();
    
    //method for loading the data if the login page is called.
    private void loadData(){
        Data.fetchInformation(ManageUser.getCurrentUserID());
        lName.setText(Data.getName());
        lEmail.setText(Data.getEmail());
        lAddress.setText(Data.getAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        lPageName = new javax.swing.JLabel();
        lNameText = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        lAddress = new javax.swing.JLabel();
        lAddressText = new javax.swing.JLabel();
        lEmailText = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        users = new javax.swing.JTable();
        btnSeeClerks = new javax.swing.JButton();
        btnSeeAdmins = new javax.swing.JButton();
        btnSeeCustomers = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lRoleInformation = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        tfProductID = new javax.swing.JTextField();
        tfUserID = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        rbSeePassword = new javax.swing.JRadioButton();
        tfPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        btnUpdateClerk = new javax.swing.JButton();
        tfProductName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfProductPrice = new javax.swing.JTextField();
        btnUpdateProduct = new javax.swing.JButton();
        btnSeeProducts = new javax.swing.JButton();
        btnSearchProduct = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setMaximumSize(new java.awt.Dimension(1620, 800));
        setMinimumSize(new java.awt.Dimension(1620, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1620, 800));

        panelBG.setBackground(new java.awt.Color(255, 255, 255));
        panelBG.setEnabled(false);
        panelBG.setLayout(null);

        panelTop.setBackground(new java.awt.Color(204, 204, 204));

        lPageName.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lPageName.setForeground(new java.awt.Color(0, 0, 0));
        lPageName.setText("Admin Page");

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPageName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1334, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addComponent(lPageName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panelBG.add(panelTop);
        panelTop.setBounds(0, 0, 1620, 80);

        lNameText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lNameText.setForeground(new java.awt.Color(0, 0, 0));
        lNameText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lNameText.setText("Name:");
        panelBG.add(lNameText);
        lNameText.setBounds(10, 90, 80, 32);

        lEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lEmail.setForeground(new java.awt.Color(0, 0, 0));
        lEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lEmail.setText("email of user");
        panelBG.add(lEmail);
        lEmail.setBounds(570, 90, 600, 32);

        lAddress.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAddress.setForeground(new java.awt.Color(0, 0, 0));
        lAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lAddress.setText("address of user");
        panelBG.add(lAddress);
        lAddress.setBounds(1070, 90, 520, 32);

        lAddressText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAddressText.setForeground(new java.awt.Color(0, 0, 0));
        lAddressText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lAddressText.setText("Address:");
        panelBG.add(lAddressText);
        lAddressText.setBounds(940, 90, 120, 32);

        lEmailText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lEmailText.setForeground(new java.awt.Color(0, 0, 0));
        lEmailText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lEmailText.setText("Email:");
        panelBG.add(lEmailText);
        lEmailText.setBounds(440, 90, 120, 32);

        lName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lName.setForeground(new java.awt.Color(0, 0, 0));
        lName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lName.setText("name of user");
        panelBG.add(lName);
        lName.setBounds(100, 90, 390, 32);

        users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Unique ID", "Name", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(users);

        panelBG.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 790, 580);

        btnSeeClerks.setText("List of Clerks");
        btnSeeClerks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeClerksActionPerformed(evt);
            }
        });
        panelBG.add(btnSeeClerks);
        btnSeeClerks.setBounds(310, 730, 160, 30);

        btnSeeAdmins.setText("List of Admins");
        btnSeeAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAdminsActionPerformed(evt);
            }
        });
        panelBG.add(btnSeeAdmins);
        btnSeeAdmins.setBounds(130, 730, 160, 30);

        btnSeeCustomers.setText("List of Customers");
        btnSeeCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeCustomersActionPerformed(evt);
            }
        });
        panelBG.add(btnSeeCustomers);
        btnSeeCustomers.setBounds(490, 730, 160, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Product ID:");
        panelBG.add(jLabel7);
        jLabel7.setBounds(920, 530, 110, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Update Product:");
        panelBG.add(jLabel2);
        jLabel2.setBounds(870, 480, 150, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Password:");
        panelBG.add(jLabel1);
        jLabel1.setBounds(920, 330, 100, 40);

        lRoleInformation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lRoleInformation.setForeground(new java.awt.Color(0, 0, 0));
        lRoleInformation.setText("(Role) Information:");
        panelBG.add(lRoleInformation);
        lRoleInformation.setBounds(910, 140, 520, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email:");
        panelBG.add(jLabel3);
        jLabel3.setBounds(960, 250, 60, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("User ID:");
        panelBG.add(jLabel4);
        jLabel4.setBounds(950, 170, 67, 30);

        tfAddress.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfAddress.setEnabled(false);
        panelBG.add(tfAddress);
        tfAddress.setBounds(1030, 290, 350, 30);

        tfProductID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        panelBG.add(tfProductID);
        tfProductID.setBounds(1030, 530, 350, 40);

        tfUserID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfUserID.setEnabled(false);
        panelBG.add(tfUserID);
        tfUserID.setBounds(1030, 170, 350, 30);

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfEmail.setEnabled(false);
        panelBG.add(tfEmail);
        tfEmail.setBounds(1030, 250, 350, 30);

        rbSeePassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSeePasswordItemStateChanged(evt);
            }
        });
        panelBG.add(rbSeePassword);
        rbSeePassword.setBounds(1350, 330, 30, 40);

        tfPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPassword.setEnabled(false);
        panelBG.add(tfPassword);
        tfPassword.setBounds(1030, 330, 350, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Address:");
        panelBG.add(jLabel5);
        jLabel5.setBounds(940, 290, 80, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Name:");
        panelBG.add(jLabel6);
        jLabel6.setBounds(960, 210, 60, 30);

        tfName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfName.setEnabled(false);
        panelBG.add(tfName);
        tfName.setBounds(1030, 210, 350, 30);

        btnUpdateClerk.setText("Update User");
        btnUpdateClerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateClerkActionPerformed(evt);
            }
        });
        panelBG.add(btnUpdateClerk);
        btnUpdateClerk.setBounds(1030, 390, 350, 40);

        tfProductName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        panelBG.add(tfProductName);
        tfProductName.setBounds(1030, 580, 350, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Name:");
        panelBG.add(jLabel8);
        jLabel8.setBounds(920, 580, 110, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Price:");
        panelBG.add(jLabel9);
        jLabel9.setBounds(920, 630, 110, 40);

        tfProductPrice.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        panelBG.add(tfProductPrice);
        tfProductPrice.setBounds(1030, 630, 350, 40);

        btnUpdateProduct.setText("Update Product");
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });
        panelBG.add(btnUpdateProduct);
        btnUpdateProduct.setBounds(1390, 630, 130, 40);

        btnSeeProducts.setText("See Products");
        btnSeeProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeProductsActionPerformed(evt);
            }
        });
        panelBG.add(btnSeeProducts);
        btnSeeProducts.setBounds(1390, 580, 130, 40);

        btnSearchProduct.setText("Search Product ID");
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });
        panelBG.add(btnSearchProduct);
        btnSearchProduct.setBounds(1390, 530, 130, 40);

        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        panelBG.add(btnAddProduct);
        btnAddProduct.setBounds(1030, 680, 160, 40);

        btnDeleteProduct.setText("Delete Product");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });
        panelBG.add(btnDeleteProduct);
        btnDeleteProduct.setBounds(1220, 680, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeeAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAdminsActionPerformed
        //This is to see the list of admins
        users.setModel(TableHandler.getAdminUsersTable());
        users.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        users.setRowSelectionAllowed(true);
        users.setColumnSelectionAllowed(false);
    }//GEN-LAST:event_btnSeeAdminsActionPerformed

    private void btnSeeClerksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeClerksActionPerformed
        //This is to see the list of clerks
        users.setModel(TableHandler.getClerkUsersTable());
        users.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        users.setRowSelectionAllowed(true);
        users.setColumnSelectionAllowed(false);
    }//GEN-LAST:event_btnSeeClerksActionPerformed

    private void btnSeeCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeCustomersActionPerformed
        //This is to see the list of customers
        users.setModel(TableHandler.getCustomerUsersTable());
        users.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        users.setRowSelectionAllowed(true);
        users.setColumnSelectionAllowed(false);
    }//GEN-LAST:event_btnSeeCustomersActionPerformed

    private void rbSeePasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSeePasswordItemStateChanged
        //this method is for hiding the password and change it to star '*' if not selected.
        if (rbSeePassword.isSelected()) {
            tfPassword.setEchoChar((char) 0);
        } else {
            tfPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_rbSeePasswordItemStateChanged

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        //This method will run every time the table users is clicked
        int selectedRow = users.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user first!");
            tfName.setText("");
            tfEmail.setText("");
            tfAddress.setText("");
            tfPassword.setText("");
            return;
        }
        //grab data directly from the selected row
        int selectedUser = (int) users.getValueAt(selectedRow, 0); //user_id
        
        //set the userID to the not enabled field
        tfUserID.setText(Integer.toString(selectedUser));
        
        Data.fetchInformation(selectedUser);
        
        if(Data.getUsername() == null && Data.getRole() == 0){
            lRoleInformation.setText("User deleted their account.");
            tfName.setText(Data.getName());
            tfEmail.setText(Data.getEmail());
            tfAddress.setText(Data.getAddress());
            tfPassword.setText("User has deleted their account.");
            
            tfName.disable();
            tfEmail.disable();
            tfAddress.disable();
            tfPassword.disable();
        } else if (Data.getRole() == 1){
            lRoleInformation.setText("Customer Information:");
            tfName.enable();
            tfEmail.enable();
            tfAddress.enable();
            tfPassword.disable();
            
            tfName.setText(Data.getName());
            tfEmail.setText(Data.getEmail());
            tfAddress.setText(Data.getAddress());
            tfPassword.setText("Unable to see their password");
        } else if (Data.getRole() == 2){
            lRoleInformation.setText("Clerk Information:");
            tfName.enable();
            tfEmail.enable();
            tfAddress.enable();
            tfPassword.enable();
            
            tfName.setText(Data.getName());
            tfEmail.setText(Data.getEmail());
            tfAddress.setText(Data.getAddress());
            tfPassword.setText(Data.getPassword());
        } else if (Data.getRole() == 3){
            lRoleInformation.setText("Admin Information:");
            tfName.enable();
            tfEmail.enable();
            tfAddress.enable();
            tfPassword.enable();
            
            tfName.setText(Data.getName());
            tfEmail.setText(Data.getEmail());
            tfAddress.setText(Data.getAddress());
            tfPassword.setText(Data.getPassword());
        } else {
            tfName.enable();
            tfEmail.enable();
            tfAddress.enable();
            tfPassword.enable();
            
            tfName.setText("");
            tfEmail.setText("");
            tfAddress.setText("");
            tfPassword.setText("");
        }
    }//GEN-LAST:event_usersMouseClicked

    private void btnUpdateClerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateClerkActionPerformed
        /*
            this method is for getting the information and then updating the users.
            although, admins cannot update customers' data since only they can do that themselves.
        */
        int userID;
        String name;
        String email;
        String address;
        String password;
        
        userID = Integer.parseInt(tfUserID.getText());
        name = tfName.getText().trim();
        email = tfEmail.getText().trim();
        address = tfAddress.getText().trim();
        password = tfPassword.getText().trim();
        
        Data.fetchInformation(userID);
        
        //would send them to a different method per role
        //role 0 = deleted users, role 1 = customers, role 2 = clerks, role 3 = admins.
        switch(Data.getRole()){
            case 0 -> {
                JOptionPane.showMessageDialog(null, "Unable to update deleted user.");
                return;
            }
            case 1 -> {
                JOptionPane.showMessageDialog(null, "You are not allowed to update customers.");
                return;
            }
            case 2 -> {
                function.updateClerk(name, email, address);
            }
            case 3 -> {
                function.updateAdmin(name, email, address);
            }
        }
        
        function.updateUser(userID, password);
        JOptionPane.showMessageDialog(null, "Successfully updated selected user's information.");
    }//GEN-LAST:event_btnUpdateClerkActionPerformed

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed
        Items item = null;
        String tempProductID = tfProductID.getText().trim();
        if (!tempProductID.isEmpty()) {
            try {
                int productID = Integer.parseInt(tempProductID);
                item = function.searchProduct(productID);
                if (item != null) {//just in case if the product doesn't exist
                    JOptionPane.showMessageDialog(null, "Product exists, getting information...");
                    tfProductName.setText(item.getProductName());
                    tfProductPrice.setText(Double.toString(item.getProductPrice()));
                } else {
                    tfProductID.setText("");
                    tfProductName.setText("");
                    tfProductPrice.setText("");
                }
            } catch (NumberFormatException e) {
                tfProductID.setText("");
                tfProductName.setText("");
                tfProductPrice.setText("");
                JOptionPane.showMessageDialog(null, "Please enter a valid number for Product ID.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fill the product ID with valid values.");
        }
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        int productID;
        String productName;
        double productPrice;
        try {
            productID = Integer.parseInt(tfProductID.getText().trim());
            productName = tfProductName.getText().trim();
            productPrice = Double.parseDouble(tfProductPrice.getText().trim());
            if (tfProductID.getText().trim().isEmpty() || tfProductName.getText().trim().isEmpty() || tfProductPrice.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill required fields of the product.");
            return;
            }
        function.addProduct(productID, productName, productPrice);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid values on the fields, please follow the format.");
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnSeeProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeProductsActionPerformed
        String productName = tfProductName.getText().trim();
        if (!tfProductName.getText().trim().isEmpty()){
            function.showProductsByName(productName);
        } else {
            JOptionPane.showMessageDialog(null, "Fill the product name field with valid values.");
            tfProductID.setText("");
            tfProductName.setText("");
            tfProductPrice.setText("");
        }
    }//GEN-LAST:event_btnSeeProductsActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        int productID;
        String productName;
        double productPrice;
        try {
            productID = Integer.parseInt(tfProductID.getText().trim());
            productName = tfProductName.getText().trim();
            productPrice = Double.parseDouble(tfProductPrice.getText().trim());
            if (tfProductID.getText().trim().isEmpty() || tfProductName.getText().trim().isEmpty() || tfProductPrice.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill required fields of the product.");
            return;
            }
        function.deleteProduct(productID);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid values on the fields, please follow the format.");
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        // Check if fields are empty first
        if (tfProductID.getText().trim().isEmpty() ||
            tfProductName.getText().trim().isEmpty() ||
            tfProductPrice.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the required fields.");
            return;
        }

        int oldProductID;
        double newPrice;
        String newName = tfProductName.getText().trim();

        //parsing Product ID and Price
        try {
            oldProductID = Integer.parseInt(tfProductID.getText().trim());
            newPrice = Double.parseDouble(tfProductPrice.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for Product ID and Price.");
            return;
        }
        
        if(!confirm.doesProductExist(oldProductID)){
            JOptionPane.showMessageDialog(null, "The product ID does not exist, make sure you have to correct one.");
            tfProductID.setText("");
            tfProductName.setText("");
            tfProductPrice.setText("");
            return;
        }

        //ask for new Product ID using showInputDialog from JOptionPane
        String input = JOptionPane.showInputDialog(null, "Enter its new Product ID:");
        if (input != null) {
            input = input.trim();
            if (!input.isEmpty()) {
                try {
                    int newProductID = Integer.parseInt(input);
                    function.updateProduct(oldProductID, newProductID, newName, newPrice);
                    JOptionPane.showMessageDialog(null, "Product updated successfully!");
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Invalid input! Please enter a valid number for the new Product ID.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "You didn't enter anything! Action cancelled.");
            }
        }
    }//GEN-LAST:event_btnUpdateProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton btnSeeAdmins;
    private javax.swing.JButton btnSeeClerks;
    private javax.swing.JButton btnSeeCustomers;
    private javax.swing.JButton btnSeeProducts;
    private javax.swing.JButton btnUpdateClerk;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAddress;
    private javax.swing.JLabel lAddressText;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEmailText;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lNameText;
    private javax.swing.JLabel lPageName;
    private javax.swing.JLabel lRoleInformation;
    private javax.swing.JPanel panelBG;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton rbSeePassword;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfProductID;
    private javax.swing.JTextField tfProductName;
    private javax.swing.JTextField tfProductPrice;
    private javax.swing.JTextField tfUserID;
    private javax.swing.JTable users;
    // End of variables declaration//GEN-END:variables
}
