package UI;

import Core.CartItem;
import Core.Confirmation;
import Core.Functions;
import Core.TableHandler;
import User.Data;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mellisa
 */
public class ClerkPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClerkPage.class.getName());

    private List<CartItem> cart = new ArrayList<>();
    private Functions function = new Functions();
    private Confirmation confirm = new Confirmation();
    
    /**
     * Creates new form ClerkPage
     */
    public ClerkPage() {
        initComponents();
        loadProductTable();
        loadData();
    }

    private void loadData(){
        lClerk.setText(Data.getName());
    }
    
    private void loadProductTable(){
        productList.setModel(TableHandler.getProductTable());
        productList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        productList.setRowSelectionAllowed(true);
        productList.setColumnSelectionAllowed(false);
    }
    
    public void refreshCartTable() {
        
         DefaultTableModel model = new DefaultTableModel(
            new String[]{"Product ID", "Product Name", "Price", "Quantity"}, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
                //not allowing editing of cells
            };
         
            for (CartItem item : cart) {
                model.addRow(new Object[]{
                    item.getProductId(),
                    item.getProductName(),
                    item.getPrice(),
                    item.getQuantity()
                });
            }
            
        basketTable.setModel(model);
        
        basketTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        basketTable.setRowSelectionAllowed(true);
        basketTable.setColumnSelectionAllowed(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        lPageName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JTable();
        tfSearchProduct = new javax.swing.JTextField();
        lTotalText = new javax.swing.JLabel();
        lTotalPrice = new javax.swing.JLabel();
        lTotalQuantity = new javax.swing.JLabel();
        lBasketText = new javax.swing.JLabel();
        btnSeeAll = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        basketTable = new javax.swing.JTable();
        lSearchText = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JToggleButton();
        tfQuantity = new javax.swing.JTextField();
        tfProductPrice = new javax.swing.JTextField();
        tfProductID = new javax.swing.JTextField();
        tfProductName = new javax.swing.JTextField();
        btnDeleteItem = new javax.swing.JToggleButton();
        btnClearFields = new javax.swing.JToggleButton();
        lClerk = new javax.swing.JLabel();
        lCash = new javax.swing.JLabel();
        lCheckoutCustomerID = new javax.swing.JLabel();
        lQuantity = new javax.swing.JLabel();
        lProductID = new javax.swing.JLabel();
        lProductName = new javax.swing.JLabel();
        lPriceItem = new javax.swing.JLabel();
        lCurrentClerk = new javax.swing.JLabel();
        lProceedCheckout = new javax.swing.JLabel();
        tfCash = new javax.swing.JTextField();
        tfCheckoutCustomer = new javax.swing.JTextField();
        tfCustomerID = new javax.swing.JTextField();
        lSearchCustomer = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JToggleButton();
        btnSearch = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Page");
        setMaximumSize(new java.awt.Dimension(1620, 800));
        setMinimumSize(new java.awt.Dimension(1620, 800));
        setSize(new java.awt.Dimension(1620, 800));

        panelBG.setBackground(new java.awt.Color(255, 255, 255));
        panelBG.setLayout(null);

        panelTop.setBackground(new java.awt.Color(204, 204, 204));

        lPageName.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lPageName.setForeground(new java.awt.Color(0, 0, 0));
        lPageName.setText("Clerk Page");

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPageName)
                .addContainerGap(1375, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addComponent(lPageName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panelBG.add(panelTop);
        panelTop.setBounds(0, 0, 1620, 80);

        productList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productList);

        panelBG.add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 390, 600);

        tfSearchProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSearchProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchProductKeyReleased(evt);
            }
        });
        panelBG.add(tfSearchProduct);
        tfSearchProduct.setBounds(170, 90, 250, 40);

        lTotalText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTotalText.setForeground(new java.awt.Color(0, 0, 0));
        lTotalText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lTotalText.setText("Total Amount:");
        panelBG.add(lTotalText);
        lTotalText.setBounds(900, 100, 170, 30);

        lTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTotalPrice.setForeground(new java.awt.Color(102, 255, 102));
        lTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lTotalPrice.setText("00.00");
        panelBG.add(lTotalPrice);
        lTotalPrice.setBounds(1080, 100, 190, 30);

        lTotalQuantity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTotalQuantity.setForeground(new java.awt.Color(0, 0, 0));
        lTotalQuantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lTotalQuantity.setText("0");
        panelBG.add(lTotalQuantity);
        lTotalQuantity.setBounds(1080, 740, 190, 30);

        lBasketText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lBasketText.setForeground(new java.awt.Color(0, 0, 0));
        lBasketText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lBasketText.setText("Current Items :");
        panelBG.add(lBasketText);
        lBasketText.setBounds(900, 740, 170, 30);

        btnSeeAll.setText("See All Product");
        btnSeeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAllActionPerformed(evt);
            }
        });
        panelBG.add(btnSeeAll);
        btnSeeAll.setBounds(30, 753, 390, 30);

        basketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price", "Quantity"
            }
        ));
        basketTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                basketTableMouseClicked(evt);
            }
        });
        basketTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                basketTablePropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(basketTable);

        panelBG.add(jScrollPane2);
        jScrollPane2.setBounds(900, 130, 590, 600);

        lSearchText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lSearchText.setForeground(new java.awt.Color(0, 0, 0));
        lSearchText.setText("Search Product:");
        panelBG.add(lSearchText);
        lSearchText.setBounds(30, 86, 140, 40);

        btnAddItem.setText("Add to Items");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });
        panelBG.add(btnAddItem);
        btnAddItem.setBounds(580, 320, 130, 40);

        tfQuantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfQuantity.setText("0");
        panelBG.add(tfQuantity);
        tfQuantity.setBounds(470, 320, 80, 40);

        tfProductPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfProductPrice.setEnabled(false);
        panelBG.add(tfProductPrice);
        tfProductPrice.setBounds(470, 260, 390, 40);

        tfProductID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfProductID.setEnabled(false);
        panelBG.add(tfProductID);
        tfProductID.setBounds(470, 140, 390, 40);

        tfProductName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfProductName.setEnabled(false);
        panelBG.add(tfProductName);
        tfProductName.setBounds(470, 200, 390, 40);

        btnDeleteItem.setText("Delete From Items");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });
        panelBG.add(btnDeleteItem);
        btnDeleteItem.setBounds(730, 320, 130, 40);

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });
        panelBG.add(btnClearFields);
        btnClearFields.setBounds(470, 370, 390, 40);

        lClerk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lClerk.setForeground(new java.awt.Color(0, 0, 0));
        lClerk.setText("clerk name");
        panelBG.add(lClerk);
        lClerk.setBounds(550, 80, 310, 20);

        lCash.setForeground(new java.awt.Color(0, 0, 0));
        lCash.setText("Cash");
        panelBG.add(lCash);
        lCash.setBounds(470, 650, 110, 30);

        lCheckoutCustomerID.setForeground(new java.awt.Color(0, 0, 0));
        lCheckoutCustomerID.setText("Customer ID");
        panelBG.add(lCheckoutCustomerID);
        lCheckoutCustomerID.setBounds(470, 590, 110, 30);

        lQuantity.setForeground(new java.awt.Color(0, 0, 0));
        lQuantity.setText("Quantity");
        panelBG.add(lQuantity);
        lQuantity.setBounds(470, 300, 110, 30);

        lProductID.setForeground(new java.awt.Color(0, 0, 0));
        lProductID.setText("Product ID");
        panelBG.add(lProductID);
        lProductID.setBounds(470, 120, 70, 30);

        lProductName.setForeground(new java.awt.Color(0, 0, 0));
        lProductName.setText("Product Name");
        panelBG.add(lProductName);
        lProductName.setBounds(470, 180, 110, 30);

        lPriceItem.setForeground(new java.awt.Color(0, 0, 0));
        lPriceItem.setText("Price of Item");
        panelBG.add(lPriceItem);
        lPriceItem.setBounds(470, 240, 110, 30);

        lCurrentClerk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lCurrentClerk.setForeground(new java.awt.Color(0, 0, 0));
        lCurrentClerk.setText("Current Clerk:");
        panelBG.add(lCurrentClerk);
        lCurrentClerk.setBounds(470, 80, 80, 20);

        lProceedCheckout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lProceedCheckout.setForeground(new java.awt.Color(0, 0, 0));
        lProceedCheckout.setText("Proceed Checkout:");
        panelBG.add(lProceedCheckout);
        lProceedCheckout.setBounds(470, 560, 120, 30);

        tfCash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelBG.add(tfCash);
        tfCash.setBounds(470, 670, 390, 40);

        tfCheckoutCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelBG.add(tfCheckoutCustomer);
        tfCheckoutCustomer.setBounds(470, 610, 390, 40);

        tfCustomerID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelBG.add(tfCustomerID);
        tfCustomerID.setBounds(470, 490, 250, 40);

        lSearchCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lSearchCustomer.setForeground(new java.awt.Color(0, 0, 0));
        lSearchCustomer.setText("Search Customer:");
        panelBG.add(lSearchCustomer);
        lSearchCustomer.setBounds(470, 460, 100, 30);

        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        panelBG.add(btnCheckout);
        btnCheckout.setBounds(490, 720, 350, 40);

        btnSearch.setText("Search ID or Name");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        panelBG.add(btnSearch);
        btnSearch.setBounds(730, 490, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAllActionPerformed
        // TODO add your handling code here:
        loadProductTable();
        tfSearchProduct.setText("");
    }//GEN-LAST:event_btnSeeAllActionPerformed

    private void tfSearchProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchProductKeyReleased

        String searchProduct = tfSearchProduct.getText().trim();
        
        if (!searchProduct.isEmpty()){ //code inside will run if field search is not empty
            
            if (searchProduct.matches("\\d+")) {
                //if digit, clerk is searching via ID
                productList.setModel(TableHandler.getSearchedProduct(Integer.parseInt(searchProduct)));
            } else {
                productList.setModel(TableHandler.getSearchedProduct(searchProduct));
            }
            
        }
    }//GEN-LAST:event_tfSearchProductKeyReleased

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        
        int selectedRow = productList.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product first!");
            return;
        }

        // Grab data directly from the selected row
        int selectedProductID = (int) productList.getValueAt(selectedRow, 0);      //product_id
        String selectedProductName = (String) productList.getValueAt(selectedRow, 1); //prod_name
        double selectedProductPrice = (double) productList.getValueAt(selectedRow, 2); //prod_price

        //grabs the quantity from the textfield quantity
        int quantity;
        try {
            quantity = Integer.parseInt(tfQuantity.getText());
            if (quantity <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid quantity!");
            return;
        }
        //code will run if the quantity is valid
        
        //check if the product selected is already in the item list
        boolean itemIsAlreadyHere = false;
        
        for (CartItem item : cart) {
            if (item.getProductId() == selectedProductID) {
                //overwrite or fix the mistake
                item.setQuantity(quantity); //overwrite the old quantity to the new one
                itemIsAlreadyHere = true;
                break;
            }
        }

        //if the product isnt found make a new row
        if (!itemIsAlreadyHere) {
            cart.add(new CartItem(selectedProductID, selectedProductName, selectedProductPrice, quantity));
        }
        
        // Refresh the JTable to show updated cart
        refreshCartTable();
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void displayProductOnUI(int selectedProductID, String selectedProductName, double selectedProductPrice){
        String displayProductID = Integer.toString(selectedProductID);
        String displayProductName = selectedProductName;
        String displayProductPrice = Double.toString(selectedProductPrice);
        tfProductID.setText(displayProductID);
        tfProductName.setText(displayProductName);
        tfProductPrice.setText(displayProductPrice);
        tfQuantity.setText("0");
    }
    
    private void productListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productListMouseClicked
        
        int selectedRow = productList.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product first!");
            return;
        }
        //grab data directly from the selected row
        int selectedProductID = (int) productList.getValueAt(selectedRow, 0);      //product_id
        String selectedProductName = (String) productList.getValueAt(selectedRow, 1); //prod_name
        double selectedProductPrice = (double) productList.getValueAt(selectedRow, 2); //prod_price
        
        displayProductOnUI(selectedProductID, selectedProductName, selectedProductPrice);
        
    }//GEN-LAST:event_productListMouseClicked

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        tfProductID.setText("");
        tfProductName.setText("");
        tfProductPrice.setText("");
        tfQuantity.setText("0");
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void basketTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basketTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = basketTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product first!");
            return;
        }

        //grab data directly from the selected row
        int selectedProductID = (int) basketTable.getValueAt(selectedRow, 0);      //product_id
        String selectedProductName = (String) basketTable.getValueAt(selectedRow, 1); //prod_name
        double selectedProductPrice = (double) basketTable.getValueAt(selectedRow, 2); //prod_price
        int quantity = (int) basketTable.getValueAt(selectedRow, 3);
        
        displayProductOnUI(selectedProductID, selectedProductName, selectedProductPrice);
        tfQuantity.setText(Integer.toString(quantity));
    }//GEN-LAST:event_basketTableMouseClicked

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        int selectedRow = basketTable.getSelectedRow(); //get the selected row in the basket table
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product to remove!");
            return;
        }
        //remove from in-memory cart
        cart.remove(selectedRow);
        //refresh tje table
        refreshCartTable();
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    public void updateCartTotals() {
        int totalQuantity = 0;
        double totalPrice = 0;
        for (CartItem item : cart) {
            totalQuantity += item.getQuantity();
            totalPrice += item.getPrice() * item.getQuantity();
        }
        DecimalFormat df = new DecimalFormat("#,##0.00");
        lTotalPrice.setText("₱ " + df.format(totalPrice));
        lTotalQuantity.setText(String.valueOf(totalQuantity));
}
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchCustomer = tfCustomerID.getText().trim();
        if (!searchCustomer.isEmpty()){ //code inside will run if field customer search is not empty
            if (searchCustomer.matches("\\d+")) {
                int customerID = Integer.parseInt(tfCustomerID.getText().trim());
                function.searchCustomer(customerID);
            } else {
                String customerName = tfCustomerID.getText().trim();
                function.searchCustomer(customerName);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void basketTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_basketTablePropertyChange
        // TODO add your handling code here:
        updateCartTotals();
    }//GEN-LAST:event_basketTablePropertyChange

    public void checkOut(){
        //rest muna here is the last code
        
    }
    
    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        int customerID = Integer.parseInt(tfCheckoutCustomer.getText().trim());
        if (confirm.isCustomerExisting(customerID) == false){
            JOptionPane.showMessageDialog(null, "Customer with that ID does not exist.");
            return;
        }
        if (!tfCash.getText().trim().isEmpty()){
            try {
                double totalPrice = 0;
                double cash = Double.parseDouble(tfCash.getText().trim());
                for (CartItem item : cart) {
                    totalPrice += item.getPrice() * item.getQuantity();
                }
                if (cash >= totalPrice) {
                    checkOut();
                } else {
                    JOptionPane.showMessageDialog(null, "Insufficient cash amount.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter a valid cash");
                tfCash.setText("0");
            }
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClerkPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable basketTable;
    private javax.swing.JToggleButton btnAddItem;
    private javax.swing.JToggleButton btnCheckout;
    private javax.swing.JToggleButton btnClearFields;
    private javax.swing.JToggleButton btnDeleteItem;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JButton btnSeeAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lBasketText;
    private javax.swing.JLabel lCash;
    private javax.swing.JLabel lCheckoutCustomerID;
    private javax.swing.JLabel lClerk;
    private javax.swing.JLabel lCurrentClerk;
    private javax.swing.JLabel lPageName;
    private javax.swing.JLabel lPriceItem;
    private javax.swing.JLabel lProceedCheckout;
    private javax.swing.JLabel lProductID;
    private javax.swing.JLabel lProductName;
    private javax.swing.JLabel lQuantity;
    private javax.swing.JLabel lSearchCustomer;
    private javax.swing.JLabel lSearchText;
    private javax.swing.JLabel lTotalPrice;
    private javax.swing.JLabel lTotalQuantity;
    private javax.swing.JLabel lTotalText;
    private javax.swing.JPanel panelBG;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTable productList;
    private javax.swing.JTextField tfCash;
    private javax.swing.JTextField tfCheckoutCustomer;
    private javax.swing.JTextField tfCustomerID;
    private javax.swing.JTextField tfProductID;
    private javax.swing.JTextField tfProductName;
    private javax.swing.JTextField tfProductPrice;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfSearchProduct;
    // End of variables declaration//GEN-END:variables
}
