package UI;

import Core.Functions;
import Core.TableHandler;
import User.Data;
import User.ManageUser;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class CustomerPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerPage.class.getName());

    /**
     * Creates new form CustomerPage
     */
    public CustomerPage() {
        initComponents();
        loadData();
        loadOrderData();
    }
    
    private Functions function = new Functions();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void loadData(){
        
        Data.fetchInformation(ManageUser.getCurrentUserID());
        
        lName.setText(Data.getName());
        lEmail.setText(Data.getEmail());
        lAddress.setText(Data.getAddress());
        
        tfPassword.setText(Data.getPassword());
        tfName.setText(Data.getName());
        tfEmail.setText(Data.getEmail());
        tfAddress.setText(Data.getAddress());
    }
    
    public void loadOrderData() {
        
        purchaseListTable.setModel(TableHandler.getCustomerPurchaseTable());
        
        double total = 0;

        for (int row = 0; row < purchaseListTable.getRowCount(); row++) {
            int quantity = Integer.parseInt(purchaseListTable.getValueAt(row, 3).toString()); // column 3 = quantity
            double price = Double.parseDouble(purchaseListTable.getValueAt(row, 4).toString()); // column 4 = price

            total += quantity * price;
        }

        DecimalFormat df = new DecimalFormat("#,##0.00");
        lMoneySpent.setText("₱ " + df.format(total));
            
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        lPageName = new javax.swing.JLabel();
        lLogOut = new javax.swing.JLabel();
        lAddressText = new javax.swing.JLabel();
        lAddress = new javax.swing.JLabel();
        lEmailText = new javax.swing.JLabel();
        lNameText = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseListTable = new javax.swing.JTable();
        lText1 = new javax.swing.JLabel();
        rbSeePassword = new javax.swing.JRadioButton();
        tfPassword = new javax.swing.JPasswordField();
        lText2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lText3 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lText5 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        btnDeleteAccount = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnUpdateAccount = new javax.swing.JButton();
        lMoneySpent = new javax.swing.JLabel();
        lText4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Page");
        setMaximumSize(new java.awt.Dimension(1620, 800));
        setMinimumSize(new java.awt.Dimension(1620, 800));
        setSize(new java.awt.Dimension(1620, 800));

        panelBG.setBackground(new java.awt.Color(255, 255, 255));
        panelBG.setLayout(null);

        panelTop.setBackground(new java.awt.Color(204, 204, 204));

        lPageName.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lPageName.setForeground(new java.awt.Color(0, 0, 0));
        lPageName.setText("Customer Page");

        lLogOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lLogOut.setForeground(new java.awt.Color(0, 0, 0));
        lLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/logout icon.png"))); // NOI18N
        lLogOut.setText("Log-out");
        lLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lLogOutMouseClicked(evt);
            }
        });
        lLogOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lLogOutKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPageName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1070, Short.MAX_VALUE)
                .addComponent(lLogOut)
                .addGap(106, 106, 106))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lLogOut)
                    .addComponent(lPageName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panelBG.add(panelTop);
        panelTop.setBounds(0, 0, 1620, 80);

        lAddressText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAddressText.setForeground(new java.awt.Color(0, 0, 0));
        lAddressText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lAddressText.setText("Address:");
        panelBG.add(lAddressText);
        lAddressText.setBounds(950, 90, 120, 32);

        lAddress.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAddress.setForeground(new java.awt.Color(0, 0, 0));
        lAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lAddress.setText("address of user");
        panelBG.add(lAddress);
        lAddress.setBounds(1080, 90, 520, 32);

        lEmailText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lEmailText.setForeground(new java.awt.Color(0, 0, 0));
        lEmailText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lEmailText.setText("Email:");
        panelBG.add(lEmailText);
        lEmailText.setBounds(450, 90, 120, 32);

        lNameText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lNameText.setForeground(new java.awt.Color(0, 0, 0));
        lNameText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lNameText.setText("Name:");
        panelBG.add(lNameText);
        lNameText.setBounds(20, 90, 80, 32);

        lName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lName.setForeground(new java.awt.Color(0, 0, 0));
        lName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lName.setText("name of user");
        panelBG.add(lName);
        lName.setBounds(110, 90, 390, 32);

        lEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lEmail.setForeground(new java.awt.Color(0, 0, 0));
        lEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lEmail.setText("email of user");
        panelBG.add(lEmail);
        lEmail.setBounds(580, 90, 600, 32);

        purchaseListTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        purchaseListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Date", "Order ID", "Product Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(purchaseListTable);

        panelBG.add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 1000, 610);

        lText1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lText1.setForeground(new java.awt.Color(0, 0, 0));
        lText1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lText1.setText("Password:");
        panelBG.add(lText1);
        lText1.setBounds(1040, 170, 90, 25);

        rbSeePassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSeePasswordItemStateChanged(evt);
            }
        });
        panelBG.add(rbSeePassword);
        rbSeePassword.setBounds(1480, 210, 20, 20);

        tfPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelBG.add(tfPassword);
        tfPassword.setBounds(1040, 200, 470, 40);

        lText2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lText2.setForeground(new java.awt.Color(0, 0, 0));
        lText2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lText2.setText("Name:");
        panelBG.add(lText2);
        lText2.setBounds(1040, 240, 60, 25);

        tfName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelBG.add(tfName);
        tfName.setBounds(1040, 270, 470, 40);

        lText3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lText3.setForeground(new java.awt.Color(0, 0, 0));
        lText3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lText3.setText("Email:");
        panelBG.add(lText3);
        lText3.setBounds(1040, 310, 60, 25);

        tfEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelBG.add(tfEmail);
        tfEmail.setBounds(1040, 340, 470, 40);

        lText5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lText5.setForeground(new java.awt.Color(0, 0, 0));
        lText5.setText("Total Money Spent");
        panelBG.add(lText5);
        lText5.setBounds(1060, 650, 330, 50);

        tfAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelBG.add(tfAddress);
        tfAddress.setBounds(1040, 410, 470, 40);

        btnDeleteAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDeleteAccount.setText("Delete Account");
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });
        panelBG.add(btnDeleteAccount);
        btnDeleteAccount.setBounds(1170, 530, 210, 40);

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRefresh.setText("Refresh Table");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        panelBG.add(btnRefresh);
        btnRefresh.setBounds(1170, 580, 210, 40);

        btnUpdateAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateAccount.setText("Update Account");
        btnUpdateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAccountActionPerformed(evt);
            }
        });
        panelBG.add(btnUpdateAccount);
        btnUpdateAccount.setBounds(1170, 480, 210, 40);

        lMoneySpent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lMoneySpent.setForeground(new java.awt.Color(102, 255, 102));
        lMoneySpent.setText("₱ 00.00");
        panelBG.add(lMoneySpent);
        lMoneySpent.setBounds(1090, 700, 460, 30);

        lText4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lText4.setForeground(new java.awt.Color(0, 0, 0));
        lText4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lText4.setText("Address:");
        panelBG.add(lText4);
        lText4.setBounds(1040, 380, 80, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbSeePasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSeePasswordItemStateChanged
        if (rbSeePassword.isSelected()) {
            tfPassword.setEchoChar((char) 0);
        } else {
            tfPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_rbSeePasswordItemStateChanged

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadData();
        loadOrderData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAccountActionPerformed

        String password = tfPassword.getText().trim();
        String name = tfName.getText().trim();
        String email = tfEmail.getText().trim();
        String address = tfAddress.getText().trim();
        
        function.updateUser(password);
        function.updateCustomer(name, email, address);
    }//GEN-LAST:event_btnUpdateAccountActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
        int result = JOptionPane.showConfirmDialog(
            null, 
            "Are you sure you want to delete your account?", 
            "Confirm Delete", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE
        );
        if (result == JOptionPane.YES_OPTION) {
            function.deleteAccount(); // your method
            String message = "Successfully deleted your account.";
            JOptionPane.showMessageDialog(null, message, "Account Deletion", JOptionPane.INFORMATION_MESSAGE);
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        } else {
            String message = "Account deletion has been cancelled.";
            JOptionPane.showMessageDialog(null, message, "Account Deletion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void lLogOutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lLogOutKeyPressed

    }//GEN-LAST:event_lLogOutKeyPressed

    private void lLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLogOutMouseClicked
        ManageUser.clearSession();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdateAccount;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAddress;
    private javax.swing.JLabel lAddressText;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEmailText;
    private javax.swing.JLabel lLogOut;
    private javax.swing.JLabel lMoneySpent;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lNameText;
    private javax.swing.JLabel lPageName;
    private javax.swing.JLabel lText1;
    private javax.swing.JLabel lText2;
    private javax.swing.JLabel lText3;
    private javax.swing.JLabel lText4;
    private javax.swing.JLabel lText5;
    private javax.swing.JPanel panelBG;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTable purchaseListTable;
    private javax.swing.JRadioButton rbSeePassword;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
