package UI;

import Core.Confirmation;
import DatabaseConnection.DBConnection;
import User.Data;
import User.ManageUser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mellisa
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        checkDBConnection(); //for making sure in OOP since
    }
    
    //called the Confirmation class to confirm if the credentials are correct.
    private Confirmation confirmation = new Confirmation();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new javax.swing.JPanel();
        StoreName = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lPassword = new javax.swing.JLabel();
        rbSeePassword = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JToggleButton();
        lDontHaveAnAccount = new javax.swing.JLabel();
        lCreateAccount = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 350));

        panelBG.setBackground(new java.awt.Color(255, 255, 255));
        panelBG.setLayout(null);

        StoreName.setFont(new java.awt.Font("Rockwell", 1, 75)); // NOI18N
        StoreName.setForeground(new java.awt.Color(0, 0, 0));
        StoreName.setText("ZStore");
        panelBG.add(StoreName);
        StoreName.setBounds(232, 0, 234, 89);

        lUsername.setBackground(new java.awt.Color(255, 255, 255));
        lUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lUsername.setForeground(new java.awt.Color(0, 0, 0));
        lUsername.setText("Username:");
        panelBG.add(lUsername);
        lUsername.setBounds(105, 95, 90, 25);

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        panelBG.add(tfUsername);
        tfUsername.setBounds(105, 126, 500, 38);

        lPassword.setBackground(new java.awt.Color(255, 255, 255));
        lPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lPassword.setForeground(new java.awt.Color(0, 0, 0));
        lPassword.setText("Password:");
        panelBG.add(lPassword);
        lPassword.setBounds(105, 170, 90, 25);

        rbSeePassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSeePasswordItemStateChanged(evt);
            }
        });
        panelBG.add(rbSeePassword);
        rbSeePassword.setBounds(570, 210, 20, 20);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelBG.add(btnLogin);
        btnLogin.setBounds(175, 261, 350, 40);

        lDontHaveAnAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lDontHaveAnAccount.setForeground(new java.awt.Color(102, 153, 255));
        lDontHaveAnAccount.setText("Don't have an account?");
        panelBG.add(lDontHaveAnAccount);
        lDontHaveAnAccount.setBounds(224, 307, 130, 16);

        lCreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lCreateAccount.setForeground(new java.awt.Color(102, 153, 255));
        lCreateAccount.setText("Create an account");
        lCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lCreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCreateAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lCreateAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lCreateAccountMouseExited(evt);
            }
        });
        panelBG.add(lCreateAccount);
        lCreateAccount.setBounds(360, 307, 100, 16);

        tfPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        panelBG.add(tfPassword);
        tfPassword.setBounds(110, 200, 490, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(714, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //to ensure or warn maam about the connection.
    private void checkDBConnection() {
        if (DBConnection.getConnection() == null) {
            
            StringBuilder message = new StringBuilder();
            
            message.append("Unable to connect to the MySQL database!\n\n");
            message.append("Please make sure:\n");
            message.append("1. You have added the MySQL Connector / JAR file to the project.\n");
            message.append("   - In NetBeans: Press the '>' icon on the left of the project name\n");
            message.append("        -> right-click Libraries -> ADD JAR/Folder -> select the mysql jar file\n");
            message.append("   I will provide the jar file in the folder \"Important Files\"\n");
            message.append("   if somehow it still doesnt work, please download the mysql jar file on the official website [https://www.mysql.com/products/connector/]\n");
            message.append("   select JDBC Driver for MySQL -> Platform Independent -> select .zip -> extract it -> then add the jar file to the Libraries\n");
            message.append("2. Your MySQL server is running.\n");
            message.append("3. The database export has been successfully imported on your unit.\n");
            message.append("4. The URL, USER, and PASSWORD variable on the DBConnection class aligns with your database\n");
            System.out.println("Check the DBConnection class and see if the variables; URL, USER, PASSWORD is correct with your database po.");
            message.append("5. The username and password in my DBConnection class in getConnection method.\n");
            message.append("   - aligns with your username and password on your mysql application.\n\n");
            message.append("Note from us: If there is still an error regarding the connection of the database\n");
            message.append("    Please don't hesitate to message us po, we will surely make it work.\n\n");
            message.append("Do you want to test the connection again?");

            int option = JOptionPane.showConfirmDialog(
                null, 
                message.toString(), 
                "Database Connection Error", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (option == JOptionPane.YES_OPTION) {
                //retry connection so it wont be a hassle for maam Razel
                if (DBConnection.getConnection() != null) {
                    JOptionPane.showMessageDialog(null, "Connection successful!");
                } else {
                    JOptionPane.showMessageDialog(null, "Still unable to connect. Check your settings.");
                }
            }
        }
    }
    
    private void lCreateAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCreateAccountMouseEntered
        lCreateAccount.setText("<html><u>" + "Create an account" + "</u></html>");
    }//GEN-LAST:event_lCreateAccountMouseEntered

    private void lCreateAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCreateAccountMouseExited
        lCreateAccount.setText("Create an account");
    }//GEN-LAST:event_lCreateAccountMouseExited

    //if user will log in and will check if the account exists and the credentials are correct.
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = tfUsername.getText().trim();
        String password = tfPassword.getText().trim();
        
        if (confirmation.checkLogin(username, password) == true) {
            Data.fetchInformation(ManageUser.getCurrentUserID());
            int role = Data.getRole();
            switch (role) {
                case 1 -> {
                    ManageUser.gettingCurrentCustomerID();
                    //debugging.
//                    System.out.println("Current user's customer id: " + ManageUser.getCurrentCustomerID());
                    CustomerPage customer = new CustomerPage();
                    customer.setExtendedState(CustomerPage.MAXIMIZED_BOTH);
                    customer.setVisible(true);
                    this.dispose();
                }
                case 2 -> {
                    ManageUser.gettingCurrentClerkID();
                    //debugging
//                    System.out.println("Current Clerk ID: " + ManageUser.getCurrentClerkID());
//                    System.out.println("Current User ID: " + ManageUser.getCurrentUserID());
                    ClerkPage clerk = new ClerkPage();
                    clerk.setExtendedState(ClerkPage.MAXIMIZED_BOTH);
                    clerk.setVisible(true);
                    this.dispose();
                }
                case 3 -> {
                    AdminPage admin = new AdminPage();
                    admin.setExtendedState(AdminPage.MAXIMIZED_BOTH);
                    admin.setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    //create new account label
    private void lCreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCreateAccountMouseClicked
        SignUp signUp = new SignUp();
        signUp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lCreateAccountMouseClicked

    //this method is for hiding the password and change it to star '*' if not selected.
    private void rbSeePasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSeePasswordItemStateChanged
        if (rbSeePassword.isSelected()) {
            tfPassword.setEchoChar((char) 0);
        } else {
            tfPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_rbSeePasswordItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StoreName;
    private javax.swing.JToggleButton btnLogin;
    private javax.swing.JLabel lCreateAccount;
    private javax.swing.JLabel lDontHaveAnAccount;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel panelBG;
    private javax.swing.JRadioButton rbSeePassword;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
