package UI;

import Core.Functions;
import User.ManageUser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mellisa
 */
public class SignUp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp.class.getName());

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }
    
    private Functions function = new Functions();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleGroup = new javax.swing.ButtonGroup();
        panelBG = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbCustomer = new javax.swing.JRadioButton();
        rbClerk = new javax.swing.JRadioButton();
        rbAdmin = new javax.swing.JRadioButton();
        btnCreateAccount = new javax.swing.JButton();
        lDontHaveAnAccount = new javax.swing.JLabel();
        lSignIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        panelBG.setBackground(new java.awt.Color(255, 255, 255));
        panelBG.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome new user!");
        panelBG.add(jLabel1);
        jLabel1.setBounds(20, 10, 560, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username:");
        panelBG.add(jLabel2);
        jLabel2.setBounds(90, 50, 90, 40);

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelBG.add(tfUsername);
        tfUsername.setBounds(190, 50, 250, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email:");
        panelBG.add(jLabel3);
        jLabel3.setBounds(120, 280, 60, 40);

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelBG.add(tfEmail);
        tfEmail.setBounds(190, 280, 250, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password:");
        panelBG.add(jLabel4);
        jLabel4.setBounds(90, 100, 90, 40);

        tfPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelBG.add(tfPassword);
        tfPassword.setBounds(190, 100, 250, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name:");
        panelBG.add(jLabel5);
        jLabel5.setBounds(120, 230, 60, 40);

        tfName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelBG.add(tfName);
        tfName.setBounds(190, 230, 250, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Address:");
        panelBG.add(jLabel6);
        jLabel6.setBounds(100, 330, 80, 40);

        tfAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelBG.add(tfAddress);
        tfAddress.setBounds(190, 330, 250, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Role:");
        panelBG.add(jLabel7);
        jLabel7.setBounds(180, 150, 270, 31);

        roleGroup.add(rbCustomer);
        rbCustomer.setForeground(new java.awt.Color(0, 0, 0));
        rbCustomer.setText("Customer");
        panelBG.add(rbCustomer);
        rbCustomer.setBounds(190, 180, 80, 21);

        roleGroup.add(rbClerk);
        rbClerk.setForeground(new java.awt.Color(0, 0, 0));
        rbClerk.setText("Clerk");
        panelBG.add(rbClerk);
        rbClerk.setBounds(290, 180, 60, 21);

        roleGroup.add(rbAdmin);
        rbAdmin.setForeground(new java.awt.Color(0, 0, 0));
        rbAdmin.setText("Admin");
        panelBG.add(rbAdmin);
        rbAdmin.setBounds(370, 180, 70, 21);

        btnCreateAccount.setForeground(new java.awt.Color(0, 0, 0));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        panelBG.add(btnCreateAccount);
        btnCreateAccount.setBounds(190, 380, 250, 40);

        lDontHaveAnAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lDontHaveAnAccount.setForeground(new java.awt.Color(102, 153, 255));
        lDontHaveAnAccount.setText("Already have an account?");
        panelBG.add(lDontHaveAnAccount);
        lDontHaveAnAccount.setBounds(220, 420, 150, 16);

        lSignIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lSignIn.setForeground(new java.awt.Color(102, 153, 255));
        lSignIn.setText("Sign-in");
        lSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lSignInMouseExited(evt);
            }
        });
        panelBG.add(lSignIn);
        lSignIn.setBounds(370, 420, 40, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSignInMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lSignInMouseClicked

    private void lSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSignInMouseEntered
        lSignIn.setText("<html><u>" + "Sign-in" + "</u></html>");
    }//GEN-LAST:event_lSignInMouseEntered

    private void lSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSignInMouseExited
        lSignIn.setText("Sign-in");
    }//GEN-LAST:event_lSignInMouseExited

    private boolean isFieldValid(){
        if (tfUsername.getText().trim().isEmpty() || tfPassword.getText().trim().isEmpty() || tfName.getText().trim().isEmpty() ||
           tfEmail.getText().trim().isEmpty() || tfAddress.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the fields to continue.");
            return false;
        }
        return true;
    }
    
    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        
        if (isFieldValid() == false){
            return;
        }
        
        int role;
        if (rbCustomer.isSelected()){
            role = 1;
        } else if (rbClerk.isSelected()){
            role = 2;
        } else if (rbAdmin.isSelected()){
            role = 3;
        } else {
            JOptionPane.showMessageDialog(null, "Please select a role to continue.");
            return;
        }
        
        String username = tfUsername.getText().trim();
        String password = tfPassword.getText().trim();
        String name = tfName.getText().trim();
        String email = tfEmail.getText().trim();
        String address = tfAddress.getText().trim();
        
        if (ManageUser.isUsernameDuplicated(username) == true) {
            return;
        };
        
        function.addUser(username, password, role, name, email, address);
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lDontHaveAnAccount;
    private javax.swing.JLabel lSignIn;
    private javax.swing.JPanel panelBG;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbClerk;
    private javax.swing.JRadioButton rbCustomer;
    private javax.swing.ButtonGroup roleGroup;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
